<ul class='list-group'>
    <li class='list-group-item'> 
        <?php echo "Nombre: " . $dataJugadores->Nombre; ?>
    </li>
    <li class='list-group-item'> 
        <?php echo "Posición: " . $dataJugadores->Posicion; ?>
    </li>
    <li class='list-group-item'> 
        <?php echo "Fecha de nacimiento: " . $dataJugadores->Nacimiento; ?>
    </li>
    <li class='list-group-item'> 
        <?php echo "Nacionalidad: " . $dataJugadores->Nacionalidad; ?>
    </li>
    <li class='list-group-item'> 
        <?php echo "Club: " . $dataJugadores->club_nombre; ?>
    </li>
    <li class='list-group-item'> 
        <?php echo "Liga: " . $dataJugadores->Liga; ?>
    </li>
</ul>
</li>
</ul>