<?php if (isset($_SESSION['ID_USER'])) { ?>
    <form action="agregarJugador" method="POST">
        <input name="nombre" type="text" placeholder="Nombre" require>
        <input name="posicion" type="text" placeholder="Posicion" require>
        <input name="nacimiento" type="date" placeholder="Fecha" require>
        <input name="nacionalidad" type="text" placeholder="Nacionalidad" require>
        <?php
        require_once 'app/controllers/clubes.controller.php';
        $clubesController = new clubController();
        $clubes = $clubesController->getAll();
        ?>

        <select name="club" id="">
            <option hidden>Club</option>
            <?php
            $ClubesMostrados = [];
            foreach ($clubes as $club) {

                if (!in_array($club->Club, $ClubesMostrados)) {
                    $ClubesMostrados[] = $club->Club;
            ?>
                    <option value="<?php echo $club->Club; ?>"><?php echo $club->Club; ?></option>
            <?php
                }
            }
            ?>
        </select>
        <button type="submit">Agregar</button>
    </form>
<?php
} else { ?>
    <p>No tienes permiso para agregar jugadores.</p>
<?php }
