<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();  // Solo inicia la sesión si aún no está activa
}
?>
<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="">WEB 2 - TP2</a>
            <span class="navbar-text"></span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="jugadores">Jugadores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="clubes">Clubes</a>
                    </li>               
                    <?php if (isset($_SESSION['USER'])): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="CerrarSesion">Salir</a>
                        </li>
                        <li class="nav-item">
                            <span class="nav-link">
                                <?php echo $_SESSION['USER']; // Muestra el nombre del usuario ?>
                            </span>
                        </li>
                    <?php else: ?>
                        <li class="nav-item">
                            <a class="nav-link" href="IniciarSesion">Iniciar Sesión</a>
                        </li>
                    <?php endif; ?>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="CerrarSesion">Salir</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="IniciarSesion">Iniciar Sesion</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>
</header>
</body>
